version: '3.8'

services:
  backend:
    image: aminhelloworld/timemanager-back:latest
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: ${DATABASE_URL}

  frontend:
    image: aminhelloworld/timemanager-front:latest
    ports:
      - "4001:80"